spring:
  data:
    mongodb:
      database: jobota
      auto-index-creation: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  main:
    web-application-type: reactive
logLevel: DEBUG
mongock:
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
  change-logs-scan-package: com.zigzag.jobotaserver.migrations